### ISSUE TITLE
Using MD5 hash to check for update 

### ISSUE THREAD

**Issue by labros-zotos** [webhookdb/webhookdb#905]
Assuming an API endpoint doesn't provide a created_at or updated_at timestamps.
Is there a way to use something like an MD5 hash (of the response JSON) comparison between an old API response and a new one during polling in order to determine if the response has changed?
I cannot find anything like that in the docs.

**Comment by rgalanakis** [comment]
Hi there, great question, sorry for the delayed response.
Generally what we do is this in the replicators:
```
  def _update_where_expr
    return self.qualified_table_sequel_identifier[:data] !~ Sequel[:excluded][:data]
  end
```

That says, "if the raw API value (webhook, API response, etc) has not changed, do not update the row". Would something like that work for your use case?

**Comment by labros-zotos** [comment]
Thank you for your reply. 
Yes that seems perfect for my use case.
I will try to combine it together with the following from the docs since I don't have any timestamps from the API:
```
Webhookdb::Replicator::Column.new(
:row_updated_at,
TIMESTAMP,
defaulter: :now,
index: true,
optional: true,
)
```
It should work as expected. I will build a test case tomorrow to test it out.
Thank you again!
